on:
  push:
    branches:
      - main

name: CI/CD
jobs:
  build-test-and-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: ' SetUp java'
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: 'Maven Package'
        run: mvn --batch-mode --update-snapshots package

      - name: 'Az Docker Login'
        uses: Azure/docker-login@v1
        with:
          login-server: index.docker.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
          docker build . -t jpdecastro/cicd-demo:${{ github.sha }}
          docker push jpdecastro/cicd-demo:${{ github.sha }}

      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: 'Run Az ClI Command'
        run: |
          az aks show --resource-group rg-accelerator-aks --name akscluster-nrmn-1

      - uses: azure/setup-kubectl@v2.0

      - uses: Azure/aks-set-context@v1
        with:
          method: service-account
          k8s-url: https://acldys-dae32c32.hcp.westeurope.azmk8s.io:443
          k8s-secret: default-token-hkx9v
        id: setcontext

      - uses: Azure/k8s-create-secret@v1.1
        with:
          container-registry-url: index.docker.io
          container-registry-username: ${{ secrets.REGISTRY_USERNAME }}
          container-registry-password: ${{ secrets.REGISTRY_PASSWORD }}
          secret-name: docker-secret

      - uses: Azure/k8s-deploy@v3.1
        with:
          action: deploy #options: deploy, promote, reject
          manifests: |
            manifests/deployment.yml
          strategy: basic #options: basic, canary, blue-green
          images: |
            jpdecastro/cicd-demo:${{ github.sha }}
          imagepullsecrets: |
            docker-secret